In [21]:
import torch

retrieve_indices = torch.tensor([[ 0,  6, -1, -1, -1, -1, -1, -1],
        [ 0,  9, -1, -1, -1, -1, -1, -1],
        [ 0,  1, 12, -1, -1, -1, -1, -1],
        [ 0,  8, 20, -1, -1, -1, -1, -1],
        [ 0,  3, 15, 21, -1, -1, -1, -1],
        [ 0,  3, 15, 24, -1, -1, -1, -1],
        [ 0,  3, 15, 25, -1, -1, -1, -1],
        [ 0,  2, 13, 27, -1, -1, -1, -1],
        [ 0,  2, 13, 28, -1, -1, -1, -1],
        [ 0,  4, 16, 33, -1, -1, -1, -1],
        [ 0,  4, 17, 35, -1, -1, -1, -1],
        [ 0,  5, 18, 36, -1, -1, -1, -1],
        [ 0,  1, 11, 34, 43, -1, -1, -1],
        [ 0,  3, 15, 23, 44, -1, -1, -1],
        [ 0,  1, 10, 30, 46, -1, -1, -1],
        [ 0,  7, 19, 37, 47, -1, -1, -1],
        [ 0,  1, 10, 29, 38, 49, -1, -1],
        [ 0,  3, 15, 22, 42, 52, -1, -1],
        [ 0,  2, 13, 26, 45, 53, -1, -1],
        [ 0,  2, 14, 31, 40, 54, -1, -1]]).reshape(-1,10,8)

tree_logits = torch.rand([2,60,10])

In [22]:
retrieve_indices.shape

torch.Size([2, 10, 8])

In [28]:
logits1 = tree_logits[0, retrieve_indices[0]]
logits1

tensor([[[0.6916, 0.7867, 0.3361, 0.5022, 0.2626, 0.5902, 0.2748, 0.0987,
          0.8934, 0.9067],
         [0.3758, 0.1602, 0.4092, 0.0282, 0.0323, 0.0975, 0.9064, 0.5958,
          0.9386, 0.0232],
         [0.8281, 0.6095, 0.9305, 0.6493, 0.9499, 0.3167, 0.7562, 0.2676,
          0.3489, 0.2386],
         [0.8281, 0.6095, 0.9305, 0.6493, 0.9499, 0.3167, 0.7562, 0.2676,
          0.3489, 0.2386],
         [0.8281, 0.6095, 0.9305, 0.6493, 0.9499, 0.3167, 0.7562, 0.2676,
          0.3489, 0.2386],
         [0.8281, 0.6095, 0.9305, 0.6493, 0.9499, 0.3167, 0.7562, 0.2676,
          0.3489, 0.2386],
         [0.8281, 0.6095, 0.9305, 0.6493, 0.9499, 0.3167, 0.7562, 0.2676,
          0.3489, 0.2386],
         [0.8281, 0.6095, 0.9305, 0.6493, 0.9499, 0.3167, 0.7562, 0.2676,
          0.3489, 0.2386]],

        [[0.6916, 0.7867, 0.3361, 0.5022, 0.2626, 0.5902, 0.2748, 0.0987,
          0.8934, 0.9067],
         [0.6820, 0.7125, 0.7975, 0.9224, 0.2894, 0.9324, 0.3043, 0.1414,
          0.315

In [29]:
logits1.shape

torch.Size([10, 8, 10])

In [25]:
bsz = 2
batch_idx = torch.arange(bsz)[:, None, None]
logits = tree_logits[batch_idx, retrieve_indices, :]

In [26]:
logits.shape

torch.Size([2, 10, 8, 10])

In [27]:
logits

tensor([[[[0.6916, 0.7867, 0.3361,  ..., 0.0987, 0.8934, 0.9067],
          [0.3758, 0.1602, 0.4092,  ..., 0.5958, 0.9386, 0.0232],
          [0.8281, 0.6095, 0.9305,  ..., 0.2676, 0.3489, 0.2386],
          ...,
          [0.8281, 0.6095, 0.9305,  ..., 0.2676, 0.3489, 0.2386],
          [0.8281, 0.6095, 0.9305,  ..., 0.2676, 0.3489, 0.2386],
          [0.8281, 0.6095, 0.9305,  ..., 0.2676, 0.3489, 0.2386]],

         [[0.6916, 0.7867, 0.3361,  ..., 0.0987, 0.8934, 0.9067],
          [0.6820, 0.7125, 0.7975,  ..., 0.1414, 0.3158, 0.7749],
          [0.8281, 0.6095, 0.9305,  ..., 0.2676, 0.3489, 0.2386],
          ...,
          [0.8281, 0.6095, 0.9305,  ..., 0.2676, 0.3489, 0.2386],
          [0.8281, 0.6095, 0.9305,  ..., 0.2676, 0.3489, 0.2386],
          [0.8281, 0.6095, 0.9305,  ..., 0.2676, 0.3489, 0.2386]],

         [[0.6916, 0.7867, 0.3361,  ..., 0.0987, 0.8934, 0.9067],
          [0.6079, 0.0314, 0.2367,  ..., 0.8138, 0.1589, 0.1018],
          [0.1107, 0.4941, 0.6894,  ..., 0

In [30]:
torch.equal(logits[0],logits1)

True

In [31]:
input = torch.rand([2,1,2])

In [32]:
output = torch.rand([2,5,2])

In [33]:
input

tensor([[[0.1295, 0.3053]],

        [[0.1829, 0.4956]]])

In [34]:
output

tensor([[[0.1321, 0.0702],
         [0.2131, 0.5176],
         [0.9263, 0.0466],
         [0.0656, 0.2289],
         [0.5949, 0.2068]],

        [[0.7661, 0.7987],
         [0.6763, 0.9217],
         [0.3953, 0.3030],
         [0.3997, 0.9544],
         [0.6198, 0.1226]]])

In [35]:
tgt = input.repeat_interleave(5,dim=1)

In [40]:
dst = output[...]

In [41]:
dst.copy_(tgt, non_blocking=True)

tensor([[[0.1295, 0.3053],
         [0.1295, 0.3053],
         [0.1295, 0.3053],
         [0.1295, 0.3053],
         [0.1295, 0.3053]],

        [[0.1829, 0.4956],
         [0.1829, 0.4956],
         [0.1829, 0.4956],
         [0.1829, 0.4956],
         [0.1829, 0.4956]]])

In [ ]:
torch.equal(input, output[:,1:2,...])

True