In [21]:
import torch

retrieve_indices = torch.tensor([[ 0,  6, -1, -1, -1, -1, -1, -1],
        [ 0,  9, -1, -1, -1, -1, -1, -1],
        [ 0,  1, 12, -1, -1, -1, -1, -1],
        [ 0,  8, 20, -1, -1, -1, -1, -1],
        [ 0,  3, 15, 21, -1, -1, -1, -1],
        [ 0,  3, 15, 24, -1, -1, -1, -1],
        [ 0,  3, 15, 25, -1, -1, -1, -1],
        [ 0,  2, 13, 27, -1, -1, -1, -1],
        [ 0,  2, 13, 28, -1, -1, -1, -1],
        [ 0,  4, 16, 33, -1, -1, -1, -1],
        [ 0,  4, 17, 35, -1, -1, -1, -1],
        [ 0,  5, 18, 36, -1, -1, -1, -1],
        [ 0,  1, 11, 34, 43, -1, -1, -1],
        [ 0,  3, 15, 23, 44, -1, -1, -1],
        [ 0,  1, 10, 30, 46, -1, -1, -1],
        [ 0,  7, 19, 37, 47, -1, -1, -1],
        [ 0,  1, 10, 29, 38, 49, -1, -1],
        [ 0,  3, 15, 22, 42, 52, -1, -1],
        [ 0,  2, 13, 26, 45, 53, -1, -1],
        [ 0,  2, 14, 31, 40, 54, -1, -1]]).reshape(-1,10,8)

tree_logits = torch.rand([2,60,10])

In [22]:
retrieve_indices.shape

torch.Size([2, 10, 8])

In [28]:
logits1 = tree_logits[0, retrieve_indices[0]]
logits1

tensor([[[0.6916, 0.7867, 0.3361, 0.5022, 0.2626, 0.5902, 0.2748, 0.0987,
          0.8934, 0.9067],
         [0.3758, 0.1602, 0.4092, 0.0282, 0.0323, 0.0975, 0.9064, 0.5958,
          0.9386, 0.0232],
         [0.8281, 0.6095, 0.9305, 0.6493, 0.9499, 0.3167, 0.7562, 0.2676,
          0.3489, 0.2386],
         [0.8281, 0.6095, 0.9305, 0.6493, 0.9499, 0.3167, 0.7562, 0.2676,
          0.3489, 0.2386],
         [0.8281, 0.6095, 0.9305, 0.6493, 0.9499, 0.3167, 0.7562, 0.2676,
          0.3489, 0.2386],
         [0.8281, 0.6095, 0.9305, 0.6493, 0.9499, 0.3167, 0.7562, 0.2676,
          0.3489, 0.2386],
         [0.8281, 0.6095, 0.9305, 0.6493, 0.9499, 0.3167, 0.7562, 0.2676,
          0.3489, 0.2386],
         [0.8281, 0.6095, 0.9305, 0.6493, 0.9499, 0.3167, 0.7562, 0.2676,
          0.3489, 0.2386]],

        [[0.6916, 0.7867, 0.3361, 0.5022, 0.2626, 0.5902, 0.2748, 0.0987,
          0.8934, 0.9067],
         [0.6820, 0.7125, 0.7975, 0.9224, 0.2894, 0.9324, 0.3043, 0.1414,
          0.315

In [29]:
logits1.shape

torch.Size([10, 8, 10])

In [25]:
bsz = 2
batch_idx = torch.arange(bsz)[:, None, None]
logits = tree_logits[batch_idx, retrieve_indices, :]

In [26]:
logits.shape

torch.Size([2, 10, 8, 10])

In [27]:
logits

tensor([[[[0.6916, 0.7867, 0.3361,  ..., 0.0987, 0.8934, 0.9067],
          [0.3758, 0.1602, 0.4092,  ..., 0.5958, 0.9386, 0.0232],
          [0.8281, 0.6095, 0.9305,  ..., 0.2676, 0.3489, 0.2386],
          ...,
          [0.8281, 0.6095, 0.9305,  ..., 0.2676, 0.3489, 0.2386],
          [0.8281, 0.6095, 0.9305,  ..., 0.2676, 0.3489, 0.2386],
          [0.8281, 0.6095, 0.9305,  ..., 0.2676, 0.3489, 0.2386]],

         [[0.6916, 0.7867, 0.3361,  ..., 0.0987, 0.8934, 0.9067],
          [0.6820, 0.7125, 0.7975,  ..., 0.1414, 0.3158, 0.7749],
          [0.8281, 0.6095, 0.9305,  ..., 0.2676, 0.3489, 0.2386],
          ...,
          [0.8281, 0.6095, 0.9305,  ..., 0.2676, 0.3489, 0.2386],
          [0.8281, 0.6095, 0.9305,  ..., 0.2676, 0.3489, 0.2386],
          [0.8281, 0.6095, 0.9305,  ..., 0.2676, 0.3489, 0.2386]],

         [[0.6916, 0.7867, 0.3361,  ..., 0.0987, 0.8934, 0.9067],
          [0.6079, 0.0314, 0.2367,  ..., 0.8138, 0.1589, 0.1018],
          [0.1107, 0.4941, 0.6894,  ..., 0

In [30]:
torch.equal(logits[0],logits1)

True

In [7]:
import torch
input = torch.rand([6,1,8,20,12])

In [8]:
output = torch.rand([6,5,8,20,12])

In [10]:
incld = 10
bsz = 5
tgt = input[..., :incld, :].repeat_interleave(bsz, dim=1)
dst = torch.narrow(output, -2, 0, incld)
dst.copy_(tgt, non_blocking=True)

tensor([[[[[2.5708e-01, 7.6071e-01, 6.3814e-01,  ..., 7.1188e-01,
            5.5501e-02, 9.1963e-01],
           [1.6443e-02, 9.4052e-01, 2.9013e-01,  ..., 7.3780e-01,
            6.4402e-01, 2.3348e-02],
           [4.4161e-01, 8.4348e-01, 2.1103e-01,  ..., 8.3978e-01,
            4.2458e-01, 2.0083e-01],
           ...,
           [2.5544e-01, 7.5792e-01, 6.5043e-01,  ..., 9.2297e-01,
            9.3364e-01, 9.5832e-01],
           [2.3041e-01, 6.3562e-01, 1.0636e-01,  ..., 3.5894e-01,
            1.9032e-02, 3.5877e-01],
           [3.6812e-01, 3.3176e-01, 2.7992e-01,  ..., 5.7419e-01,
            4.8567e-02, 3.9744e-01]],

          [[9.3367e-01, 6.2393e-01, 1.1821e-02,  ..., 8.9749e-01,
            2.2982e-01, 7.7615e-01],
           [5.4298e-02, 5.5937e-01, 7.9747e-01,  ..., 2.9716e-01,
            8.3742e-01, 1.6335e-01],
           [4.8885e-01, 4.2004e-01, 1.2521e-01,  ..., 8.0576e-01,
            2.8295e-01, 5.1721e-01],
           ...,
           [3.6455e-01, 8.1322e-01, 8.4

In [11]:
torch.equal(input[...,:incld,:], output[:,1:2,:,:incld,:])

True

In [4]:
import torch
torch.tensor([[[0,0],[1,1]]])[:,-1:]

tensor([[[1, 1]]])

In [5]:
tl = []
tl.append(torch.rand([1,5]))
tl.append(torch.rand([1,3]))

In [6]:
tl

[tensor([[0.3344, 0.7345, 0.1452, 0.4017, 0.5997]]),
 tensor([[0.0195, 0.3304, 0.2933]])]

In [7]:
torch.cat(tl, dim = 0)

RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 5 but got size 3 for tensor number 1 in the list.