In [1]:
import torch

retrieve_indices = torch.tensor([[ 0,  6, -1, -1, -1, -1, -1, -1],
        [ 0,  9, -1, -1, -1, -1, -1, -1],
        [ 0,  1, 12, -1, -1, -1, -1, -1],
        [ 0,  8, 20, -1, -1, -1, -1, -1],
        [ 0,  3, 15, 21, -1, -1, -1, -1],
        [ 0,  3, 15, 24, -1, -1, -1, -1],
        [ 0,  3, 15, 25, -1, -1, -1, -1],
        [ 0,  2, 13, 27, -1, -1, -1, -1],
        [ 0,  2, 13, 28, -1, -1, -1, -1],
        [ 0,  4, 16, 33, -1, -1, -1, -1],
        [ 0,  4, 17, 35, -1, -1, -1, -1],
        [ 0,  5, 18, 36, -1, -1, -1, -1],
        [ 0,  1, 11, 34, 43, -1, -1, -1],
        [ 0,  3, 15, 23, 44, -1, -1, -1],
        [ 0,  1, 10, 30, 46, -1, -1, -1],
        [ 0,  7, 19, 37, 47, -1, -1, -1],
        [ 0,  1, 10, 29, 38, 49, -1, -1],
        [ 0,  3, 15, 22, 42, 52, -1, -1],
        [ 0,  2, 13, 26, 45, 53, -1, -1],
        [ 0,  2, 14, 31, 40, 54, -1, -1]]).reshape(-1,10,8)

tree_logits = torch.rand([2,60,10])

In [2]:
retrieve_indices.shape

torch.Size([2, 10, 8])

In [3]:
logits1 = tree_logits[0, retrieve_indices[0]]
logits1

tensor([[[0.8949, 0.7685, 0.0534, 0.0170, 0.9295, 0.3549, 0.4422, 0.7560,
          0.4017, 0.8954],
         [0.3722, 0.7397, 0.3409, 0.5924, 0.0157, 0.7785, 0.1664, 0.2158,
          0.6656, 0.5781],
         [0.5851, 0.8738, 0.1360, 0.1931, 0.9669, 0.8539, 0.1277, 0.7131,
          0.0126, 0.4808],
         [0.5851, 0.8738, 0.1360, 0.1931, 0.9669, 0.8539, 0.1277, 0.7131,
          0.0126, 0.4808],
         [0.5851, 0.8738, 0.1360, 0.1931, 0.9669, 0.8539, 0.1277, 0.7131,
          0.0126, 0.4808],
         [0.5851, 0.8738, 0.1360, 0.1931, 0.9669, 0.8539, 0.1277, 0.7131,
          0.0126, 0.4808],
         [0.5851, 0.8738, 0.1360, 0.1931, 0.9669, 0.8539, 0.1277, 0.7131,
          0.0126, 0.4808],
         [0.5851, 0.8738, 0.1360, 0.1931, 0.9669, 0.8539, 0.1277, 0.7131,
          0.0126, 0.4808]],

        [[0.8949, 0.7685, 0.0534, 0.0170, 0.9295, 0.3549, 0.4422, 0.7560,
          0.4017, 0.8954],
         [0.7773, 0.0744, 0.0927, 0.4852, 0.4021, 0.0484, 0.1806, 0.2453,
          0.235

In [4]:
logits1.shape

torch.Size([10, 8, 10])

In [5]:
bsz = 2
# batch_idx = torch.arange(bsz)[:, None, None]
# logits = tree_logits[batch_idx, retrieve_indices, :]
logits_list = [tree_logits[i, retrieve_indices[i]] for i in range(bsz)]

In [6]:
logits_list[0].shape

torch.Size([10, 8, 10])

In [7]:
logits_list

[tensor([[[0.8949, 0.7685, 0.0534, 0.0170, 0.9295, 0.3549, 0.4422, 0.7560,
           0.4017, 0.8954],
          [0.3722, 0.7397, 0.3409, 0.5924, 0.0157, 0.7785, 0.1664, 0.2158,
           0.6656, 0.5781],
          [0.5851, 0.8738, 0.1360, 0.1931, 0.9669, 0.8539, 0.1277, 0.7131,
           0.0126, 0.4808],
          [0.5851, 0.8738, 0.1360, 0.1931, 0.9669, 0.8539, 0.1277, 0.7131,
           0.0126, 0.4808],
          [0.5851, 0.8738, 0.1360, 0.1931, 0.9669, 0.8539, 0.1277, 0.7131,
           0.0126, 0.4808],
          [0.5851, 0.8738, 0.1360, 0.1931, 0.9669, 0.8539, 0.1277, 0.7131,
           0.0126, 0.4808],
          [0.5851, 0.8738, 0.1360, 0.1931, 0.9669, 0.8539, 0.1277, 0.7131,
           0.0126, 0.4808],
          [0.5851, 0.8738, 0.1360, 0.1931, 0.9669, 0.8539, 0.1277, 0.7131,
           0.0126, 0.4808]],
 
         [[0.8949, 0.7685, 0.0534, 0.0170, 0.9295, 0.3549, 0.4422, 0.7560,
           0.4017, 0.8954],
          [0.7773, 0.0744, 0.0927, 0.4852, 0.4021, 0.0484, 0.1806, 0.2

In [8]:
torch.equal(logits_list[0],logits1)

True

In [7]:
import torch
input = torch.rand([6,1,8,20,12])

In [8]:
output = torch.rand([6,5,8,20,12])

In [10]:
incld = 10
bsz = 5
tgt = input[..., :incld, :].repeat_interleave(bsz, dim=1)
dst = torch.narrow(output, -2, 0, incld)
dst.copy_(tgt, non_blocking=True)

tensor([[[[[2.5708e-01, 7.6071e-01, 6.3814e-01,  ..., 7.1188e-01,
            5.5501e-02, 9.1963e-01],
           [1.6443e-02, 9.4052e-01, 2.9013e-01,  ..., 7.3780e-01,
            6.4402e-01, 2.3348e-02],
           [4.4161e-01, 8.4348e-01, 2.1103e-01,  ..., 8.3978e-01,
            4.2458e-01, 2.0083e-01],
           ...,
           [2.5544e-01, 7.5792e-01, 6.5043e-01,  ..., 9.2297e-01,
            9.3364e-01, 9.5832e-01],
           [2.3041e-01, 6.3562e-01, 1.0636e-01,  ..., 3.5894e-01,
            1.9032e-02, 3.5877e-01],
           [3.6812e-01, 3.3176e-01, 2.7992e-01,  ..., 5.7419e-01,
            4.8567e-02, 3.9744e-01]],

          [[9.3367e-01, 6.2393e-01, 1.1821e-02,  ..., 8.9749e-01,
            2.2982e-01, 7.7615e-01],
           [5.4298e-02, 5.5937e-01, 7.9747e-01,  ..., 2.9716e-01,
            8.3742e-01, 1.6335e-01],
           [4.8885e-01, 4.2004e-01, 1.2521e-01,  ..., 8.0576e-01,
            2.8295e-01, 5.1721e-01],
           ...,
           [3.6455e-01, 8.1322e-01, 8.4

In [11]:
torch.equal(input[...,:incld,:], output[:,1:2,:,:incld,:])

True

In [4]:
import torch
torch.tensor([[[0,0],[1,1]]])[:,-1:]

tensor([[[1, 1]]])

In [5]:
tl = []
tl.append(torch.rand([1,5]))
tl.append(torch.rand([1,3]))

In [6]:
tl

[tensor([[0.3344, 0.7345, 0.1452, 0.4017, 0.5997]]),
 tensor([[0.0195, 0.3304, 0.2933]])]

In [12]:
draft_tokens = torch.randint(0, 100, (1, 5))
padding = (torch.zeros(1, 1, dtype=torch.long) - 1)
draft_tokens = torch.cat((draft_tokens, padding.repeat_interleave(1, dim=0)), dim=1)
draft_tokens

tensor([[ 5, 43, 75, 70, 30, -1]])

In [ ]:
import random
import torch

def evaluate_posterior(
        logits: torch.Tensor,
        candidates: torch.Tensor,
        logits_processor,
):
    accept_length = 1
    accept_cand = candidates[0][:1]
    best_candidate = 0
    for i in range(1, candidates.shape[1]):
        if i != accept_length:
            break
        adjustflag = False
        is_eq = (candidates[:, :accept_length] == accept_cand).all(dim=1) #判断与当前前缀是否符合
        fi = torch.nonzero(is_eq, as_tuple=True)[0][0] #torch.nonzero(is_eq, as_tuple=True)得到符合的路径索引，相同前缀有相同logits，任取一个即可
        gt_logits = logits[fi, i - 1][None]
        gt_logits = logits_processor(None, gt_logits)[0]
        gtp = torch.softmax(gt_logits, dim=0)
        candidates_set = []
        for j in range(candidates.shape[0]):
            if is_eq[j]:
                x = candidates[j, i]
                xi = x.item()
                if xi in candidates_set or xi == -1:
                    continue
                candidates_set.append(xi)
                r = random.random()
                px = gtp[xi]
                qx = 1.0
                acp = px / qx
                if r <= acp:
                    accept_cand = torch.cat((accept_cand, x[None]), dim=0)
                    accept_length += 1
                    best_candidate = j
                    break
                else:
                    gtp[xi] = 0
                    gtp = gtp / gtp.sum()
                    adjustflag = True
    if adjustflag and accept_length != candidates.shape[1]:
        sample_p = gtp
    else:
        gt_logits = logits[best_candidate, accept_length - 1][None]
        gt_logits = logits_processor(None, gt_logits)[0] #fix
        sample_p = torch.softmax(gt_logits, dim=0)
    return torch.tensor(best_candidate), accept_length - 1, sample_p

In [ ]:
from collections import defaultdict

def evaluate_posterior_rb(
        logits: torch.Tensor,
        candidates: torch.Tensor,
        logits_processor,
):

    stop_dict = defaultdict(float)
    prefix_set = set()
    acc = torch.zeros_like(candidates, dtype=torch.float32)
    acc[:, 0] = 1.0
    
    for i in range(1, candidates.shape[1] + 1):
        for k in range(candidates.shape[0]):
            if candidates[k, i - 1].item() == -1:
                #不存在的节点
                continue
            accept_cand = candidates[k, :i]
            if tuple(accept_cand.tolist()) in prefix_set:
                #已访问节点
                continue
            prefix_set.add(tuple(accept_cand.tolist()))
            
            P_accept = torch.prod(acc[k, :i]) #当前接受概率为前缀接受概率乘积

            is_eq = (candidates[:, :i] == accept_cand).all(dim=1) #判断与当前前缀是否符合
            fi = torch.nonzero(is_eq, as_tuple=True)[0][0] #torch.nonzero(is_eq, as_tuple=True)得到符合的路径索引，相同前缀有相同logits，任取一个即可
            gt_logits = logits[fi, i - 1][None]
            gt_logits = logits_processor(None, gt_logits)[0]
            gtp = torch.softmax(gt_logits, dim=0)
            P_reject = 1.0 #当节点为叶子结点时，子节点拒绝概率为1
            candidates_set = []
            px = 0
            for j in range(candidates.shape[0]):
                if is_eq[j]:
                    x = candidates[j, i]
                    xi = x.item()
                    if xi in candidates_set:
                        acc[j, i] = px # 填充已访问节点的所有子节点路径的接受概率
                        continue
                    if xi == -1:
                        continue
                    candidates_set.append(xi)

                    px = gtp[xi]
                    acc[j, i] = px
                    P_reject -= px
            P_stop = P_accept * P_reject
            stop_dict[i-1] += P_stop

    return stop_dict, acc

In [ ]:
leaf_num = 20
depth = 8


retrieve_indices = torch.tensor([[ 0,  1, 10, 29, 38, 48, 57, -1],
        [ 0,  1, 10, 29, 38, 49, -1, -1],
        [ 0,  1, 10, 29, 39, 51, 56, 58],
        [ 0,  1, 10, 30, 46, -1, -1, -1],
        [ 0,  1, 11, 34, 43, -1, -1, -1],
        [ 0,  1, 12, -1, -1, -1, -1, -1],
        [ 0,  2, 13, 26, 45, 53, -1, -1],
        [ 0,  2, 13, 27, -1, -1, -1, -1],
        [ 0,  2, 13, 28, -1, -1, -1, -1],
        [ 0,  2, 14, 31, 40, 54, -1, -1],
        [ 0,  3, 15, 21, -1, -1, -1, -1],
        [ 0,  3, 15, 22, 42, 52, -1, -1],
        [ 0,  3, 15, 23, 44, -1, -1, -1],
        [ 0,  3, 15, 24, -1, -1, -1, -1],
        [ 0,  3, 15, 25, -1, -1, -1, -1],
        [ 0,  4, 16, 32, 41, 50, 55, 59],
        [ 0,  4, 16, 33, -1, -1, -1, -1],
        [ 0,  4, 17, 35, -1, -1, -1, -1],
        [ 0,  5, 18, 36, -1, -1, -1, -1],
        [ 0,  6, -1, -1, -1, -1, -1, -1],
        [ 0,  7, 19, 37, 47, -1, -1, -1],
        [ 0,  8, 20, -1, -1, -1, -1, -1],
        [ 0,  9, -1, -1, -1, -1, -1, -1]])

candidates = torch.tensor(
    [[  334,    32, 71343, 48691,    25,   362, 43680,    -1],
        [  334,    32, 71343, 48691,    25, 34039,    -1,    -1],
        [  334,    32, 71343, 48691,   362, 10196,  1220,    25],
        [  334,    32, 71343, 88391,    25,    -1,    -1,    -1],
        [  334,    32, 43680, 17331,   279,    -1,    -1,    -1],
        [  334,    32, 48691,    -1,    -1,    -1,    -1,    -1],
        [  334, 51102,   279, 35342, 32245,   315,    -1,    -1],
        [  334, 51102,   279,   468,    -1,    -1,    -1,    -1],
        [  334, 51102,   279, 15852,    -1,    -1,    -1,    -1],
        [  334, 51102,   287,   279, 35342, 32245,    -1,    -1],
        [  334,  3957,  1974,   315,    -1,    -1,    -1,    -1],
        [  334,  3957,  1974, 88391,    25,   362,    -1,    -1],
        [  334,  3957,  1974, 48691,    25,    -1,    -1,    -1],
        [  334,  3957,  1974,   473,    -1,    -1,    -1,    -1],
        [  334,  3957,  1974,  2175,    -1,    -1,    -1,    -1],
        [  334,  3936, 68063,   330,  3957,  1974, 88391,    25],
        [  334,  3936, 68063, 34039,    -1,    -1,    -1,    -1],
        [  334,  3936,    25,   330,    -1,    -1,    -1,    -1],
        [  334, 49224,   311, 48691,    -1,    -1,    -1,    -1],
        [  334,  1453,    -1,    -1,    -1,    -1,    -1,    -1],
        [  334, 31192, 16222,  1056,   291,    -1,    -1,    -1],
        [  334,    39, 72054,    -1,    -1,    -1,    -1,    -1],
        [  334,     1,    -1,    -1,    -1,    -1,    -1,    -1]]
)

tree_logits = torch.rand([55,10])
logits = tree_logits[0, retrieve_indices]

1.0